In [ ]:
import tensorflow as tf

print(tf.executing_eagerly())

True


In [ ]:
a = 1
b = 3
c = tf.math.add(a,b)
print(c)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
c.numpy()

4

In [ ]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)
print("a:", a)
print("b:", b)

print(tf.rank(a))

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [ ]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)

a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)

c = tf.math.add(a,b)
print("result:", c, "\nrank: ", tf.rank(c))
print("subtract:\t", tf.math.subtract(a, b))
print("multiply:\t", tf.math.multiply(a, b))
print("divide:\t\t", tf.math.divide(a, b))
print("mod:\t\t", tf.math.mod(a, b))
print("floordiv:\t", tf.math.floordiv(a, b))

result: tf.Tensor(3.0, shape=(), dtype=float32) 
rank:  tf.Tensor(0, shape=(), dtype=int32)
subtract:	 tf.Tensor(-1.0, shape=(), dtype=float32)
multiply:	 tf.Tensor(2.0, shape=(), dtype=float32)
divide:		 tf.Tensor(0.5, shape=(), dtype=float32)
mod:		 tf.Tensor(1.0, shape=(), dtype=float32)
floordiv:	 tf.Tensor(0.0, shape=(), dtype=float32)


In [ ]:
# import library
import tensorflow as tf
import numpy as np

# define 1 dimension array 
pyList = [10., 20., 30.]
numArr = np.array([10, 15, 20])

# tensor transform
vec1 = tf.constant(pyList, dtype=tf.float32)
vec2 = tf.constant(numArr, dtype=tf.float32)

# tensor output
print("vec1: ", vec1)
print("vec2: ", vec2)

vec1:  tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2:  tf.Tensor([10. 15. 20.], shape=(3,), dtype=float32)


In [ ]:
# rank check
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# vec1: [10, 20, 30]
# vec2: [10, 15, 20]

addResult = tf.math.add(vec1, vec2)
print("result: ", addResult)
print("rank: ", tf.rank(addResult))

result:  tf.Tensor([20. 35. 50.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# vec1: [10, 20, 30]
# vec2: [10, 15, 20]

addResult = vec1 + vec2
print("result: ", addResult)
print("rank: ", tf.rank(addResult))

result:  tf.Tensor([20. 35. 50.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))
print()
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0.  5. 10.], shape=(3,), dtype=float32)
tf.Tensor([100. 300. 600.], shape=(3,), dtype=float32)
tf.Tensor([1.        1.3333334 1.5      ], shape=(3,), dtype=float32)
tf.Tensor([ 0.  5. 10.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)

tf.Tensor([ 0.  5. 10.], shape=(3,), dtype=float32)
tf.Tensor([100. 300. 600.], shape=(3,), dtype=float32)
tf.Tensor([1.        1.3333334 1.5      ], shape=(3,), dtype=float32)
tf.Tensor([ 0.  5. 10.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [ ]:
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))

print(tf.math.square(vec1))
print(vec1**3)

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(45.0, shape=(), dtype=float32)
tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)
tf.Tensor([ 1000.  8000. 27000.], shape=(3,), dtype=float32)


In [ ]:
print(tf.math.sqrt(vec2))
print(vec2**0.5)
# vec2: [10, 15, 20]
print(vec2 + 1)

tf.Tensor([3.1622777 3.8729835 4.472136 ], shape=(3,), dtype=float32)
tf.Tensor([3.1622777 3.8729835 4.472136 ], shape=(3,), dtype=float32)
tf.Tensor([11. 16. 21.], shape=(3,), dtype=float32)


In [8]:
import tensorflow as tf

data = [[10, 20], 
        [30, 40]]

mat1 = tf.constant(data)

print("rank: ", tf.rank(mat1))
print("mat: ", mat1)

rank:  tf.Tensor(2, shape=(), dtype=int32)
mat:  tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [7]:
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

mat2 = tf.stack([vec1, vec2])

print("rank: ", tf.rank(mat2))
print("mat2: ", mat2)

rank:  tf.Tensor(2, shape=(), dtype=int32)
mat2:  tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [10]:
elementMul = tf.math.multiply(mat1, mat2)

print("result: ", elementMul)
print("rank: ", tf.rank(elementMul))

tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
result:  tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
elementBc = tf.math.multiply(mat1, 3)
print("result: ", elementBc)
print("rank: ", tf.rank(elementBc))

result:  tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
matMul = tf.matmul(mat1, mat2)
print("result: ", matMul)
print("rank: ", tf.rank(matMul))

result:  tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
add1 = tf.math.add(mat1, mat2)
print("result: ", add1)
print("rank: ", tf.rank(add1))

add2 = mat1 + mat2
print("result: ", add2)
print("rank: ", tf.rank(add2))

result:  tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)
result:  tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
npArr = matMul.numpy()
print(type(npArr))
print(npArr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


In [11]:
import tensorflow as tf
import numpy as np

mat1 = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]
mat2 = [[9, 10, 11, 12], 
        [13, 14, 15, 16]]
mat3 = [[17, 18, 19, 20], 
        [21, 22, 23, 24]]

tensor1 = tf.constant([mat1, mat2, mat3])

print("rank: ", tf.rank(tensor1))
print("tensor1: ", tensor1)

rank:  tf.Tensor(3, shape=(), dtype=int32)
tensor1:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [12]:
import tensorflow as tf
import numpy as np

mat1 = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]
mat2 = [[9, 10, 11, 12], 
        [13, 14, 15, 16]]
mat3 = [[17, 18, 19, 20], 
        [21, 22, 23, 24]]

tensor2 = tf.stack([mat1, mat2, mat3])

print("rank: ", tf.rank(tensor2))
print("tensor2: ", tensor2)

rank:  tf.Tensor(3, shape=(), dtype=int32)
tensor2:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
import tensorflow as tf
import numpy as np

vec1 = [1, 2, 3, 4] 
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23, 24]

arr = [[vec1, vec2],
       [vec3, vec4],
       [vec5, vec6]]

tensor3 = tf.constant(arr)

print("rank: ", tf.rank(tensor3))
print("tensor2: ", tensor3)

rank:  tf.Tensor(3, shape=(), dtype=int32)
tensor2:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
tensor4 = tf.stack([tensor1, tensor2])

print("rank: ", tf.rank(tensor4))

print("tensor4: ", tensor4)

rank:  tf.Tensor(4, shape=(), dtype=int32)
tensor4:  tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


In [13]:
# base code
import tensorflow as tf

vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [14]:
print(vec[0])
print(vec[-1])
print(vec[:3])  # : :3 is 0~ (3-1), inclusive to exclusive

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
mat = tf.constant([[10, 20, 30],
                   [40, 50, 60]])

print(mat[0, 2])
print(mat[0, :])
print(mat[:, 1])
print(mat[:, :])


tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
#rank3 tensor
tensor = tf.constant([
          [[10, 20, 30],
           [40, 50, 60]],
          [[-10, -20, -30],
           [-40, -50, -60]]
])
print(tensor)

print(tensor[0, :, :])
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
import tensorflow as tf

tensor = tf.constant(range(0, 9))
print(tensor)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [16]:
tensor = tf.constant(range(0, 24))
print(tensor)

tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [ ]:
tensor3 = tf.reshape(tensor, [-1])
print(tensor3)

tensor4 = tf.reshape(tensor, [-1, 3, 4])
print(tensor4)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [25]:
tensor55 = tf.constant(range(0, 36))
print(tensor55)

tensor555 = tf.reshape(tensor55, [3, 2, 2, 2]) 
                                      # 2, 2: Matrix(rank:2)
                                  #  2: Tensor(rank:3)
                                # 3: Tensor(rank:4)
# 24: 2, 2, 2, 2, 2, 2
# 22: 11*2
print(tensor555)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35], shape=(36,), dtype=int32)
tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]], shape=(6, 2, 3), dtype=int32)


In [ ]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)


In [ ]:
import tensorflow as tf

tensor1 = tf.constant([[0, 1, 2], 
                       [4, 5, 6]])
print(tensor1)

tensorVar1 = tf.Variable(tensor1)
print(tensorVar1)

tf.Tensor(
[[0 1 2]
 [4 5 6]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [4, 5, 6]], dtype=int32)>


In [ ]:
print("name: ", tensorVar1.name)
print("size: ", tensorVar1.shape)
print("type: ", tensorVar1.dtype)
print("array: ", tensorVar1.numpy())

name:  Variable:0
size:  (2, 3)
type:  <dtype: 'int32'>
array:  [[0 1 2]
 [4 5 6]]


In [ ]:
tensorVar1.assign([[1, 1, 1],
                   [2, 2, 2]])
print(tensorVar1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>


In [ ]:
tensorVar2 = tf.convert_to_tensor(tensorVar1)
print(tensorVar2)

tensorVar1 + tensorVar2

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>

In [ ]:
import tensorflow as tf

g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10,))
Y = 3 * X - 2

print('X: ', X.numpy())
print('Y: ', Y.numpy())

X:  [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
Y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [ ]:
# Loss function
def calMse(X, Y, a, b):
  YPred = a * X + b
  squaredError = (YPred - Y) ** 2
  meanSquaredError = tf.reduce_mean(squaredError)

  return meanSquaredError

In [ ]:
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHES = 200

for epoch in range(1, EPOCHES+1):
  with tf.GradientTape() as tape:
    mse = calMse(X, Y, a, b)

  grad = tape.gradient(mse, {'a':a, 'b':b})
  dA, dB = grad['a'], grad['b']

  a.assign_sub(dA * 0.05)
  b.assign_sub(dB * 0.05)

  if epoch % 20 ==0:
    print("EPOCH %d - MSE: %.4f --- a: %.2f --- b: %.2f" %(epoch, mse, a, b))

EPOCH 20 - MSE: 1.1415 --- a: 1.74 --- b: -0.75
EPOCH 40 - MSE: 0.2881 --- a: 2.37 --- b: -1.37
EPOCH 60 - MSE: 0.0728 --- a: 2.69 --- b: -1.68
EPOCH 80 - MSE: 0.0184 --- a: 2.84 --- b: -1.84
EPOCH 100 - MSE: 0.0046 --- a: 2.92 --- b: -1.92
EPOCH 120 - MSE: 0.0012 --- a: 2.96 --- b: -1.96
EPOCH 140 - MSE: 0.0003 --- a: 2.98 --- b: -1.98
EPOCH 160 - MSE: 0.0001 --- a: 2.99 --- b: -1.99
EPOCH 180 - MSE: 0.0000 --- a: 2.99 --- b: -1.99
EPOCH 200 - MSE: 0.0000 --- a: 3.00 --- b: -2.00
